version: "3"

services:
  client:
    container_name: ueweb-client
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=ture
    command: 
      - npm
      - start